config/routes.rb
Rails.application.routes.draw do
  root :to => 'sections#index'

  resources :sections do
    resources :businesses
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  validates :name, :address, :website, :phone, :presence => true
  belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :name, :presence => true
  has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
    render :index
  end

  def new
    @section = Section.find(params[:section_id])
    @business = Business.new
    render :new
  end

  def create
    @section = Section.find(params[:section_id])
    @business = @section.businesses.new(business_params)
    if @business.save
      flash[:notice] = "New Business Successfully Added"
      redirect_to section_path(@section)
    else
      render :new
    end
  end

  def show
    @business = Business.find(params[:id])
  end


 private

 def business_params
   params.require(:business).permit(:name, :address, :phone, :section_id, :website)
 end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section successfully added!"
      redirect_to sections_path(@section)
    else
      render :new
    end
  end

  def new
    @section = Section.new
  end

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
    @businesses = @section.businesses
  end

  def edit
    @section = Section.find(params[:id])
    render :edit
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section Successfully Deleted"
    redirect_to sections_path
  end

  def update
    @section = Section.find(params[:id])
    @section.update_attributes(section_params)
    flash[:notice] = "Section Successfully Updated"
    redirect_to sections_path
  end

  private

  def section_params
    params.require(:section).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render "layouts/errors", :object => @business %>

<%= form_for [@section, @business] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <%= f.submit %>
<% end %>

app/views/businesses/index.html.erb
<p><%= link_to "Add a business to this section", new_section_business_path %></p>

app/views/businesses/new.html.erb
<h1>Add a new business to <%= @section.name %></h1>

<%= render 'form' %>

app/views/businesses/show.html.erb
<h1>Business <%= @business.name %> in section %= @section.name %</h1>


<h1><%= @business.name %></h1>
<h4><%= @business.address %></h4>
<h4><%= @business.phone %></h4>
<h4><%= @business.website %></h4>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for @section do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit <%= @section.name %></h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<p><%= link_to "Add a new section", new_section_path %></p>


<h1>Sections</h1>

<ul>
  <% @sections.each do |section| %>
    <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<% content_for(:title, @section.name ) %>

<h1>Businesses for: <%= @section.name %></h1>
<ul>
  <% @section.businesses.each do |business| %>
    <li><%= business.name %></li>
  <% end %>
</ul>

<p><%= link_to "Add Business", new_section_business_path(@section) %></p><p><%= link_to "Edit", edit_section_path(@section) %></p>
<p><%= link_to "Delete", section_path(@section),
                        :data => {:confirm => "Seguro?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to Sections", sections_path %></p>